# frozen_string_literal: true

class VERGEClient
  # RPC commands registered by verged and verge-qt.
  # Source: https://github.com/vergecurrency/verge/blob/master/RPC.md
  RPC_METHODS = %w[
    help
    stop
    uptime
    getmemoryinfo
    logging
    getblockchaininfo
    getchaintxstats
    getblockstats
    getbestblockhash
    getblockcount
    getblock
    getblockhash
    getblockheader
    getchaintips
    getdifficulty
    getmempoolancestors
    getmempooldescendants
    getmempoolentry
    getmempoolinfo
    getrawmempool
    gettxout
    gettxoutsetinfo
    pruneblockchain
    savemempool
    verifychain
    preciousblock
    gettxoutproof
    verifytxoutproof
    getconnectioncount
    ping
    getpeerinfo
    addnode
    disconnectnode
    getaddednodeinfo
    getnettotals
    getnetworkinfo
    setban
    listbanned
    clearbanned
    setnetworkactive
    getnodeaddresses
    getnetworkhashps
    getallnetworkhashps
    getmininginfo
    prioritisetransaction
    getblocktemplate
    decodeblock
    reserializeblock
    estimatesmartfee
    getrawtransaction
    createrawtransaction
    decoderawtransaction
    decodescript
    sendrawtransaction
    combinerawtransaction
    signrawtransaction
    signrawtransactionwithkey
    signrawtransactionwithwallet
    testmempoolaccept
    fundrawtransaction
    validateaddress
    createmultisig
    verifymessage
    signmessagewithprivkey
    setalgo
    debuginfo
    getinfo
    abandontransaction
    abortrescan
    addmultisigaddress
    backupwallet
    bumpfee
    createwallet
    dumpprivkey
    dumpwallet
    encryptwallet
    exportstealthaddress
    getaddressinfo
    getbalance
    getnewaddress
    getnewstealthaddress
    getrawchangeaddress
    getreceivedbyaddress
    gettransaction
    getunconfirmedbalance
    getwalletinfo
    importmulti
    importprivkey
    importwallet
    importaddress
    importprunedfunds
    importpubkey
    importstealthaddress
    keypoolrefill
    listaddressgroupings
    listlockunspent
    listreceivedbyaddress
    listsinceblock
    liststealthaddresses
    listtransactions
    listunspent
    listwallets
    loadwallet
    lockunspent
    sendmany
    sendtoaddress
    sendtostealthaddress
    settxfee
    signmessage
    walletlock
    walletpassphrasechange
    walletpassphrase
    removeprunedfunds
    rescanblockchain
    sethdseed
    submitblock
    generatetoaddress
    generate
    getaddressesbylabel
    getreceivedbylabel
    listlabels
    listreceivedbylabel
    setlabel
    smsgenable
    smsgdisable
    smsgoptions
    smsglocalkeys
    smsgscanchain
    smsgscanbuckets
    smsginfo
    flushsmgsdb
    smsgaddaddress
    smsgaddlocaladdress
    smsgimportprivkey
    smsggetpubkey
    smsgsend
    smsginbox
    smsgoutbox
    smsgbuckets
    smsgview
    smsg
    smsgpurge
    invalidateblock
    reconsiderblock
    waitfornewblock
    waitforblock
    waitforblockheight
    syncwithvalidationinterfacequeue
    estimaterawfee
    setmocktime
    echo
    echojson
    resendwallettransactions
  ].freeze

  METHODS = RPC_METHODS
end
